### ISSUE TITLE
GitBook Community in Google+

### ISSUE THREAD

**Issue by aleen42** [yumetodo/gitbook-plugin-markdown-parse-add-br#5]
Hi yumetodo,

I am Aleen (https://github.com/aleen42) , and the founder of GitBook Community in Google+: https://plus.google.com/communities/110696788983472771007, which aims to sharing books or plugins of GitBook, talking anything about it as well. Here I am sincerely inviting you to join us.  :punch:

**Comment by yumetodo** [comment]
@aleen42 Why don't you use https://groups.google.com ?
Google+ has **no anonymity**, and **not suited for discussion**.

For example, C++ community use Google Groups
https://groups.google.com/a/isocpp.org/forum/#!forum/std-proposals

**Comment by aleen42** [comment]
@yumetodo I think Google+ should have better interaction and designed UI. OpenCV also create a [community](https://plus.google.com/communities/106558044109618648316) in Google+.
